### ISSUE TITLE
[Event monitoring] Design a dynamic ticket sales page.

### ISSUE THREAD

**Issue by alejandrore02** [Ticket-Saver/ticketsaver-frontend#10]
- [x] Using the parameters` {name, venuesName, date, location, label}`  make a relationship with the` eventZones` and `Prices` improve integration with the netlify function with those parameters. 

- [x] sales page was protected using auth0 authentication

- [x]  Return page after success payment

## User Dashboard
1. [ ] User panel
	1. User tickets
		1. Backend 
			1. Stripes reports expose endpoint getUserPurchases (userId:string)
			2. Create lambda function to call `getUserPurchases`. This function should return `List<UserTicket>`
		2. UI
			1. Call http lambda to get  `List<UserTicket>`
			2. [ ] Display both tickets and collectibles when needed.

AC: Read ticket sales price from JSON 
-----

Add description of design stripe return page. @DanEscher98 @alejandrore02

**Comment by carlosalaniz** [comment]
https://github.com/TechDetech/ticketsaver-frontend/commit/1f2be317927119c7f4291c7663bc0f01e3504ecc

**Comment by carlosalaniz** [comment]
Stripe session problems (using poling instead of webhooks)

**Comment by carlosalaniz** [comment]
https://github.com/TechDetech/ticketsaver-frontend/pull/16
