### ISSUE TITLE
learn more button, it should show more information about the collectibles but I don't know what it should say and I also don't know if it will be stored or if it will be something static

### ISSUE THREAD

**Issue by EpsyUwU** [Ticket-Saver/ticketsaver-frontend#6]
![image](https://github.com/user-attachments/assets/7b99c6c2-45b1-4961-9a26-a4f6bf073f52)

**Comment by carlosalaniz** [comment]
What functionality? where is the data coming from?

**Comment by EpsyUwU** [comment]
> What functionality? where is the data coming from?

learn more button, it should show more information about the collectibles but I don't know what it should say and I also don't know if it will be stored or if it will be something static

**Comment by carlosalaniz** [comment]
Create copy for this area @TechDetech. maybe use chat gpt?
