### ISSUE TITLE
The design for this section does not yet exist, it must be designed in figma and then coded

### ISSUE THREAD

**Issue by EpsyUwU** [Ticket-Saver/ticketsaver-frontend#7]
User admin panel.

The design for this section does not yet exist, it must be designed in figma and then coded

![image](https://github.com/user-attachments/assets/9c64df68-b1c3-434c-a5e3-7b83cca49299)

**Comment by carlosalaniz** [comment]
Add a description of the problem

**Comment by EpsyUwU** [comment]
The design for this section does not yet exist, it must be designed in figma and then coded
