### ISSUE TITLE
Currently the event's city data is hardcoded,

### ISSUE THREAD

**Issue by EpsyUwU** [Ticket-Saver/ticketsaver-frontend#8]
There is no database yet and there is some data that I am bringing from GitHub but it is still incomplete information.

Description:
Currently the event's city data is hardcoded,

AC:
The city must be loaded from Json file.

![image](https://github.com/user-attachments/assets/6141bd3c-0ca7-442f-896a-bdff43a4ef0e)

**Comment by carlosalaniz** [comment]
Add a description of the problem. for example.

Description: 
Currently the event's city data is hardcoded, 

AC:
The city must be dynamically loaded from database.

**Comment by EpsyUwU** [comment]
There is no database yet and there is some data that I am bringing from GitHub but it is still incomplete information.

Description:
Currently the event's city data is hardcoded,

AC:
The city must be dynamically loaded from database.

> Reference in new issue

**Comment by carlosalaniz** [comment]
https://github.com/TechDetech/ticketsaver-frontend/commit/2a49c72b3ef5e7d815f33262b1d5a1466764479c
