### ISSUE TITLE
Card data is stored in localstorage so as not to make so many requests

### ISSUE THREAD

**Issue by EpsyUwU** [Ticket-Saver/ticketsaver-frontend#9]
Card data should be cached in localstorage so as not to make so many requests

![image](https://github.com/user-attachments/assets/5462d656-26d6-4934-aaa7-a5cf32bc06b7)

**Comment by carlosalaniz** [comment]
Add a description of the problem.

What data are we storing on localstorage and why

**Comment by EpsyUwU** [comment]
Card data is stored in localstorage so as not to make so many requests

**Comment by carlosalaniz** [comment]
https://github.com/TechDetech/ticketsaver-frontend/commit/963652d6bd61d39f009664653891cd49f1c312e2
